#!/bin/bash

USAGE="Usage: $0 git_repository"
if [ $# -lt 1 ]; then echo -e "$USAGE" >&2; exit 1; fi

REPOSITORY=${1}

# Goto source root.
SOURCE="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )/.."
cd "$SOURCE"

export PATH=$PATH:$SOURCE/vendor/depot_tools

fetch --nohooks chromium

pushd src
git remote add alternate "${REPOSITORY}"
git fetch alternate
popd
