#!/bin/bash

# Goto source root.
SOURCE="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )/.."
cd "$SOURCE"

export PATH=$PATH:$SOURCE/vendor/depot_tools

fetch --nohooks chromium

pushd src
git remote add lgsvl ssh://git@git.igalia.com:4428/dape/chromium-src.git
git fetch lgsvl
popd
