#!/bin/bash

USAGE="Usage: $0 version"
if [ $# -lt 1 ]; then echo -e "$USAGE" >&2; exit 1; fi

VERSION=${1#"v"}

# Goto source root.
SOURCE="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )/.."
cd "$SOURCE"

export PATH=$PATH:$SOURCE/vendor/depot_tools

cd src
git fetch lgsvl --tags
git reset --hard $VERSION
git clean -fdx
gclient sync --with_branch_heads --with_tags --delete_unversioned_trees


cd "$SOURCE"
./script/export_tarball --test-data --remove-nonessential-files chromium-$VERSION
